name: first step toward automation

on:
  push:
    branches:
      - main

jobs:
  first_job:
    runs-on: ubuntu-latest

    steps:
      - name: fetching the code
        uses: actions/checkout@v4

      - name: setup nodejs and pnpm
        uses: cybergavin/setup-nodejs-project@v1
        with:
          node-version: "22"
          cache-path: node_modules
          lock-file: package-lock.json

      - name: install packages
        run: pnpm i

      - name: start the server
        run: pnpm start
