name: first step toward automation

on:
  push:
    branches:
      - main

jobs:
  ssh_into_server_and_restart_with_updated_code:
    runs-on: ubuntu-latest

    steps:
      - name: ssh into the server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{secrets.KEY}}
          script: |
            cd ci_cd_playground
            git pull
            /home/ubuntu/.nvm/versions/node/v24.16.0/bin/pnpm i
            /home/ubuntu/.nvm/versions/node/v24.16.0/bin/pnpm start
